all:
        hosts:
                master_database:
                        ansible_user: sam
                        # ansible_user: ubuntu
                        ansible_host: 34.70.144.81
                
                fragment_chiromo:
                        ansible_user: sam
                        ansible_host: 35.222.5.84
                