all:
        hosts:
                master_database:
                        ansible_user: sam
                        ansible_host: 34.70.144.81
                
                site_kabete:
                        ansible_user: sam
                        ansible_host: 35.225.199.176
                
                site_academics:
                        ansible_user: sam
                        ansible_host: 35.188.215.224
                
                site_departments:
                        ansible_user: sam
                        ansible_host: 35.222.197.196
                